# Generated by Django 3.2 on 2023-11-02 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='estado',
            field=models.CharField(choices=[('vendido', 'vendido'), ('por vender', 'por vender')], max_length=100),
        ),
    ]
